name: Test HESMK Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Test
        run: echo "GitHub Actions workflow is running"
